#! /usr/bin/php
<?php /* -*- mode:php -*- */

require_once ("cpapi.php");

$argv = $_SERVER['argv'];

$asset_id_or_path = @$argv[1];

if ($asset_id_or_path == NULL) {
	printf ("usage: cpexists asset_id_or_path\n");
	exit (1);
}

cpapi_connect ();

$val = cpapi_exists ($asset_id_or_path);
printf ("%s\n", prettyprint_json ($val));
