#! /usr/bin/php
<?php /* -*- mode:php -*- */

require_once ("cpapi.php");

$argc = $_SERVER['argc'];
$argv = $_SERVER['argv'];

if ($argc < 2) {
	printf ("cpread asset_id\n");
	exit (1);
}

$asset_id = intval ($argv[1]);

cpapi_connect ();

$val = cpapi_read ($asset_id);
printf ("%s\n", prettyprint_json ($val));
